import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { jost, teko } from "./fonts";

export const metadata: Metadata = {
  title: "FinTrack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(jost.variable, teko.variable)}>
      <body
        className={cn(
          "min-h-screen w-screen bg-background font-sans antialiased"
        )}
      >
        {children}
      </body>
    </html>
  );
}
